<?php

class PharmacyController extends Pharmacy
{
    public function add()
    {
        return parent::add();
    }
    public function edit()
    {
        return parent::edit();
    }
    public function remove()
    {
        return parent::remove();
    }
    public function changePassword()
    {
        return parent::changePassword(); // TODO: Change the autogenerated stub
    }
}