<?php

class UsersController extends Users
{
    public function add()
    {
        return parent::add(); // TODO: Change the autogenerated stub
    }
    public function edit()
    {
        return parent::edit(); // TODO: Change the autogenerated stub
    }
    public function remove()
    {
        return parent::remove(); // TODO: Change the autogenerated stub
    }
    public function changePassword()
    {
        return parent::changePassword(); // TODO: Change the autogenerated stub
    }
}