<?php

class LocationView extends Location
{
    public function checkName()
    {
        return parent::checkName();
    }
    public function checkNameExceptThis()
    {
        return parent::checkNameExceptThis(); // TODO: Change the autogenerated stub
    }

    public function checkID()
    {
        return parent::checkID();
    }
    public function all() {
        return $this->showAll();
    }
    public function one() {
        return $this->show();
    }
}