<?php

class PharmacyView extends Pharmacy {
    public function checkNameEmail()
    {
        return parent::checkNameEmail();
    }
    public function checkNameEmailExceptThis()
    {
        return parent::checkNameEmailExceptThis(); // TODO: Change the autogenerated stub
    }

    public function checkID()
    {
        return parent::checkID();
    }
    public function all()
    {
        return $this->showAll();
    }

    public function one()
    {
        return $this->show();
    }
}